name: testsuite

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
  pull_request:

jobs:
  ubuntu:
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        uses: perl-actions/install-with-cpm@v1
        with:
          cpanfile: "cpanfile"
      - name: Makefile.PL
        run: perl -I$(pwd) Makefile.PL
      - name: make test
        run: make test

  perl-versions:
    runs-on: ubuntu-latest
    needs: [ubuntu]
    name: List Perl versions
    outputs:
      perl-versions: ${{ steps.action.outputs.perl-versions }}
    steps:
      - id: action
        uses: perl-actions/perl-versions@v1
        with:
          since-perl: v5.10
          with-devel: true
  linux:
    name: "Perl ${{ matrix.perl-version }}"
    needs: [perl-versions]
    runs-on: ubuntu-latest

    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1
      PERL_CARTON_PATH: $GITHUB_WORKSPACE/local

    strategy:
      fail-fast: false
      matrix:
        perl-version: ${{ fromJson (needs.perl-versions.outputs.perl-versions) }}
  
    container: perldocker/perl-tester:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        uses: perl-actions/install-with-cpm@v1
        with:
          sudo: false
          cpanfile: "cpanfile"
      - run: perl Makefile.PL
      - run: make
      - run: make test

  macOS:
    needs: [ubuntu, linux, windows]
    runs-on: macOS-latest

    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1
      PERL_CARTON_PATH: $GITHUB_WORKSPACE/local

    steps:
      - uses: actions/checkout@v2
      - name: Set up Perl
        run: brew install perl
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        uses: perl-actions/install-with-cpm@v1
        with:
          sudo: false
          cpanfile: "cpanfile"
      - run: perl Makefile.PL
      - run: make
      - run: make test

  windows:
    needs: [ubuntu, linux]
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Perl
        run: |
          choco install strawberryperl
          echo @"
          C:\strawberry\c\bin
          C:\strawberry\perl\site\bin
          C:\strawberry\perl\bin
          "@ |
            Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        uses: perl-actions/install-with-cpm@v1
        with:
          sudo: false
          cpanfile: "cpanfile"
      - name: perl Makefile.PL
        run: perl Makefile.PL
      - name: make
        run: make
      - name: Run Tests
        run: make test
